# Generated by Django 4.2.11 on 2024-05-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='profession',
        ),
    ]
