# Generated by Django 4.2.11 on 2024-05-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0002_rename_bio_profile_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profession',
            new_name='bio',
        ),
    ]
